[build.environment]
NPM_FLAGS = "--legacy-peer-deps"

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/"
  to = "/dashboard"
  status = 302
